/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayIndexRouteImport } from './routes/pay.index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'
import { Route as MerchantInvoiceRouteImport } from './routes/merchant.invoice'
import { Route as MerchantExportRouteImport } from './routes/merchant.export'
import { Route as PayInvoiceIdStatusRouteImport } from './routes/pay.$invoiceId.status'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIndexRoute = PayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => PayRoute,
} as any)
const MerchantInvoiceRoute = MerchantInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantExportRoute = MerchantExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => MerchantRoute,
} as any)
const PayInvoiceIdStatusRoute = PayInvoiceIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PayInvoiceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/cancel': typeof CancelRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/pay': typeof PayRouteWithChildren
  '/preview': typeof PreviewRoute
  '/merchant/export': typeof MerchantExportRoute
  '/merchant/invoice': typeof MerchantInvoiceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRouteWithChildren
  '/merchant/': typeof MerchantIndexRoute
  '/pay/': typeof PayIndexRoute
  '/pay/$invoiceId/status': typeof PayInvoiceIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/cancel': typeof CancelRoute
  '/preview': typeof PreviewRoute
  '/merchant/export': typeof MerchantExportRoute
  '/merchant/invoice': typeof MerchantInvoiceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRouteWithChildren
  '/merchant': typeof MerchantIndexRoute
  '/pay': typeof PayIndexRoute
  '/pay/$invoiceId/status': typeof PayInvoiceIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/cancel': typeof CancelRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/pay': typeof PayRouteWithChildren
  '/preview': typeof PreviewRoute
  '/merchant/export': typeof MerchantExportRoute
  '/merchant/invoice': typeof MerchantInvoiceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRouteWithChildren
  '/merchant/': typeof MerchantIndexRoute
  '/pay/': typeof PayIndexRoute
  '/pay/$invoiceId/status': typeof PayInvoiceIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/cancel'
    | '/merchant'
    | '/pay'
    | '/preview'
    | '/merchant/export'
    | '/merchant/invoice'
    | '/pay/$invoiceId'
    | '/merchant/'
    | '/pay/'
    | '/pay/$invoiceId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/cancel'
    | '/preview'
    | '/merchant/export'
    | '/merchant/invoice'
    | '/pay/$invoiceId'
    | '/merchant'
    | '/pay'
    | '/pay/$invoiceId/status'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/cancel'
    | '/merchant'
    | '/pay'
    | '/preview'
    | '/merchant/export'
    | '/merchant/invoice'
    | '/pay/$invoiceId'
    | '/merchant/'
    | '/pay/'
    | '/pay/$invoiceId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizeRoute: typeof AuthorizeRoute
  CancelRoute: typeof CancelRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  PayRoute: typeof PayRouteWithChildren
  PreviewRoute: typeof PreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/': {
      id: '/pay/'
      path: '/'
      fullPath: '/pay/'
      preLoaderRoute: typeof PayIndexRouteImport
      parentRoute: typeof PayRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof PayRoute
    }
    '/merchant/invoice': {
      id: '/merchant/invoice'
      path: '/invoice'
      fullPath: '/merchant/invoice'
      preLoaderRoute: typeof MerchantInvoiceRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/export': {
      id: '/merchant/export'
      path: '/export'
      fullPath: '/merchant/export'
      preLoaderRoute: typeof MerchantExportRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/pay/$invoiceId/status': {
      id: '/pay/$invoiceId/status'
      path: '/status'
      fullPath: '/pay/$invoiceId/status'
      preLoaderRoute: typeof PayInvoiceIdStatusRouteImport
      parentRoute: typeof PayInvoiceIdRoute
    }
  }
}

interface MerchantRouteChildren {
  MerchantExportRoute: typeof MerchantExportRoute
  MerchantInvoiceRoute: typeof MerchantInvoiceRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantExportRoute: MerchantExportRoute,
  MerchantInvoiceRoute: MerchantInvoiceRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface PayInvoiceIdRouteChildren {
  PayInvoiceIdStatusRoute: typeof PayInvoiceIdStatusRoute
}

const PayInvoiceIdRouteChildren: PayInvoiceIdRouteChildren = {
  PayInvoiceIdStatusRoute: PayInvoiceIdStatusRoute,
}

const PayInvoiceIdRouteWithChildren = PayInvoiceIdRoute._addFileChildren(
  PayInvoiceIdRouteChildren,
)

interface PayRouteChildren {
  PayInvoiceIdRoute: typeof PayInvoiceIdRouteWithChildren
  PayIndexRoute: typeof PayIndexRoute
}

const PayRouteChildren: PayRouteChildren = {
  PayInvoiceIdRoute: PayInvoiceIdRouteWithChildren,
  PayIndexRoute: PayIndexRoute,
}

const PayRouteWithChildren = PayRoute._addFileChildren(PayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizeRoute: AuthorizeRoute,
  CancelRoute: CancelRoute,
  MerchantRoute: MerchantRouteWithChildren,
  PayRoute: PayRouteWithChildren,
  PreviewRoute: PreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
