allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@tanstack/router-cli@1.167.28'
  - '@tanstack/router-core@1.171.22'
  - '@tanstack/router-generator@1.167.28'
  - '@tanstack/router-plugin@1.168.30'
  - '@rolldown/binding-android-arm64@1.2.4'
  - '@rolldown/binding-darwin-arm64@1.2.4'
  - '@rolldown/binding-darwin-x64@1.2.4'
  - '@rolldown/binding-freebsd-x64@1.2.4'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.4'
  - '@rolldown/binding-linux-arm64-gnu@1.2.4'
  - '@rolldown/binding-linux-arm64-musl@1.2.4'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.4'
  - '@rolldown/binding-linux-s390x-gnu@1.2.4'
  - '@rolldown/binding-linux-x64-gnu@1.2.4'
  - '@rolldown/binding-linux-x64-musl@1.2.4'
  - '@rolldown/binding-openharmony-arm64@1.2.4'
  - '@rolldown/binding-win32-arm64-msvc@1.2.4'
  - '@rolldown/binding-win32-x64-msvc@1.2.4'
  - rolldown@1.2.4
